services:
  mongodb:
    image: mongo:7
    container_name: mongo_foodies
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: backend_foodies
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: frontend_foodies
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo-data:
