apiVersion: v1
kind: PersistentVolume
metadata:
  name: foodies-pv
  namespace: foodies-ns
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /data/foodies   
