apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foodies-pvc
  namespace: foodies-ns
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
