apiVersion: v1
kind: Secret
metadata:
  name: foodies-secret
  namespace: foodies-ns
type: Opaque
data:
  JWT_SECRET: Zm9vZGllcyNk
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9mb29kaWVzOmZvb2RpZXMxMjNAY2x1c3RlcjAuZHV1Zmp1dS5tb25nb2RiLm5ldA==
  SELLER_PASSWORD: MTIzNA==
  CLOUDINARY_CLOUD_NAME: ZHN6cWY3Zmxz
  CLOUDINARY_API_KEY: MzE0MzE3MTY5MTMyMzQ1
  CLOUDINARY_API_SECRET: dHVVMk1OZnRoa19nV3JhVkFSTVhpaGhyZDhR
