name: Foodies CD

on:
  push:
    branches: ["main"]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:

      # - name: Checkout code
      #   uses: actions/checkout@v4 

      - name: Connect with ec2
        uses: appleboy/ssh-action@v1.0.3 
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose
            sudo usermod -aG docker ubuntu && newgrp docker
            cd foodies || git clone https://github.com/renchooz/foodies.git


            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> server/.env 
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> server/.env
            echo "SELLER_EMAIL=${{ secrets.SELLER_EMAIL }}" >> server/.env
            echo "SELLER_PASSWORD=${{ secrets.SELLER_PASSWORD }}" >> server/.env
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> server/.env
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> server/.env~
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> server/.env
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> server/.env



            git pull
            docker-compose up -d 




