name: Foodies CD

on:
  push:
    branches: ["main"]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:

      # - name: Checkout code
      #   uses: actions/checkout@v4 

      - name: Connect with ec2
        uses: atppleboy/ssh-acion@v1.0.3  
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
          script: |
            echo "hello"
            mkdir hey




