name: Foodies CD

on:
  push:
    branches: ["main"]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Connect with ec2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose git

            sudo systemctl start docker
            sudo systemctl enable docker

            # Clone if not exists
            if [ ! -d "foodies" ]; then
              git clone https://github.com/renchooz/foodies.git
            fi

            cd foodies
            git pull origin main

            # Create server .env
            cat > server/.env <<EOF
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            SELLER_EMAIL=${{ secrets.SELLER_EMAIL }}
            SELLER_PASSWORD=${{ secrets.SELLER_PASSWORD }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}
           
            EOF

            # Create client .env
            cat > client/.env <<EOF
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
            EOF

            # Check files
            ls server
            ls client

            # Docker deploy
            sudo docker-compose down
            sudo docker-compose up -d --build